services:
  postgres:
    image: postgres:16
    container_name: sleep_db
    restart: unless-stopped
    environment:
      POSTGRES_USER:     admin
      POSTGRES_PASSWORD: sleep123
      POSTGRES_DB:       sleep_analytics
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./data:/data
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  pg_data: